### PR TITLE
Pipeline edit screen buttons refactoring

### PR DESCRIPTION
**Pull request by eea03**
- new buttons introduced: Run; Debug
- buttons reordered
- composite actions buttons can be hidden by configuration property `frontend.pipeline.composite.buttons.show`

### CODE REVIEW

**Comment by skrchnavy** [comment]
@tomas-knap  if approved, it is planed to include into 2.2.0 to unify releases with eDemo. (it will be merged / cherrypicked into release branch).

**Comment by tomas-knap** [comment]
Technically its OK. I am not completely satisfied with the layout of the buttons (which may be causes by having experience with the previous layout I get used to). Users should say.  

One note:  it does not behave correctly when the resolution of screen is lower - certain buttons are not approachable. I guess that it should behave in the way that if the two groups cannot be on one line due to low resolution they should go to two lines. Please solve either now or prepare issues for that.

**Comment by tomas-knap** [comment]
SO approved with the condition that the note is solved or issue is prepared for that.

**Comment by skrchnavy** [comment]
merged into release branch in commot f6f60d40f1dae3b554fc4a07727e77c340637017

**Comment by eea03** [comment]
Actually as I tested it, it works exactly as you are suggesting. When the 2 groups don't fit on one line, second group goes to next line (see screenshot)

Tested also by @skrchnavy and could not be preproduced

canvas_small_window

**Pull request merged**
