### PR TITLE
SQL init / update SQL scripts refactoring

### PR DESCRIPTION
**Pull request by eea03**
There were tons of duplicity in SQL scripts (mostly for PostgreSQL, but also for MySQL).
Each small change in schema or data (mostly permissions) required the same change in multiple files.
This way, SQL scripts were not maintainable

This is attempt to decrease the duplicity of SQL statements and improve maintainability of SQL scripts.
Common SQL statmenets were extracted to common SQL scripts which are then executed as included scripts.

Permissions update changed - now all permissions are deleted and latest version is loaded to DB.

Related to https://github.com/UnifiedViews/Core/issues/397

### CODE REVIEW

**Comment by eea03** [comment]
One disadvantage (probably cannot be solved) of this approach for MySQL is that the scripts which include another scripts must be executed from its source directory in order to find the included scripts with relative paths. PostgreSQL have this solved, but MySQL does not support executing included files relative to the source script (what a surprise)

**Comment by eea03** [comment]
@tomas-knap: I noticed you have already updated installation guide. However, I would suggest to include something like this:

In newer versions (since 2.1.0), `data.sql` is splitted into `data-core.sql` and `data-permissions.sql`, so first change working directory to `data.sql` source directory and then execute data.sql:
```
   cd {root}/db/mysql/rdbms/
   source data.sql
```
Alternatively you can separately execute first `data-core.sql` and then `data-permissions.sql`

**Comment by mkl-eea-sk** [comment]
https://github.com/UnifiedViews/Core/issues/426
https://github.com/UnifiedViews/Core/issues/427
https://github.com/UnifiedViews/Core/issues/428

apparently, for mysql, no testing of this happened before merging into develop :(

**Comment by mkl-eea-sk** [comment]
Since this merged, I cannot install develop UV/Core with mysql...

**Comment by eea03** [comment]
Actually it was tested before merge, but merge caused these problems. Fixed in  #425.
Tested fresh installation and also update from version in master (2.0.3) with 2.1.0-update.sql

**Comment by mkl-eea-sk** [comment]
OK, i am going to retest

**Comment by mkl-eea-sk** [comment]
Thank you, works again (at least clean install with schema.sql and data.sql)

**Pull request merged**
