### PR TITLE
Fixes of permissions reimplementation

### PR DESCRIPTION
**Pull request by eea03**
Fixes of UV permissions; There is no change in the permissions concept, just fixes of specific permissions for specific functionality (replacing wrong permissions, adding missing permissions both on GUI and service layers)

@tomas-knap Please revise this ASAP as there will be consequent implementation that will change the permissions concept (organizations will be removed) and it depends on changes in this pull request

### CODE REVIEW

**Comment by tomas-knap** [comment]
@eea03 Tomas, please in the future commits, write better commit labels - having 10 commits with label "Further fixes" tells nothing. So every commit should have label which summarises the idea of the change and if possible, also tells why such change was necessary.

**Comment by tomas-knap** [comment]
@eea03 Add documentation for this change, which is mentioned in the commit messages, is it https://team.eea.sk/wiki/display/OD/Reimplementacia+opravneni ?
Is it actual - adjusted based on the changes in this pull request?

**Comment by tomas-knap** [comment]
@eea03 Ready to be merged 
@jakubklimek told me, he wants to deploy today before lunch develop branch - if possible with this pull request

**Comment by eea03** [comment]
Detailed documentation of the changes is actually in the sheet https://team.eea.sk/wiki/download/attachments/109773994/analyza_implementacie_opravneni.xls?api=v2, where specific UV functionalities are mapped to actual permissions; There are also some notes for each functionality / permission; But I will try to clean also the wiki page

**Comment by tomas-knap** [comment]
Thanks, yes, please review and adjust the wiki page (at least briefly) and also add link to this xls doc from the wiki page.

**Pull request merged**
