### PR TITLE
Implementation fo Relational Data Unit

### PR DESCRIPTION
**Pull request by skrchnavy**
Related to #274 and UnifiedViews/Plugin-DevEnv#13

### CODE REVIEW

**Comment by skrchnavy** [comment]
I suggest to move RelationalRepositoryManager from package  cz.cuni.mff.xrg.odcs.commons.app.dataunit.relational to 
package eu.unifiedviews.commons.dataunit.core

@tomas-knap / @skodape to comment/confirm
@eea03 - for info.

**Comment by skodape** [comment]
@skrchnavy Is this question only on package or also on location in some module, as the packages are somehow linked to modules.

**Comment by skrchnavy** [comment]
In the same module, only package. (There was a reason to put it in this module - @eea03  to share the reason)

**Comment by eea03** [comment]
I wanted the relational repository to be configurable via config.properties so I needed to make it a Spring bean (which would have not been possible in dataunit-relational-impl module). 
It is an equivalent of rdf RepositoryManager. Also this class is called from within this module in DataUnitFactoryImpl. 
I think this is the right module to place it, the only question should be the package to place it in.

**Comment by mkl-eea-sk** [comment]
:) well, putting dataunits, each into two separate modules. is just an MFF obsession. eea03: only one thing remains, can you imagine, that module-test, which ensures unit testing for DPUs, can use your dataunit? We will discuss on monday.

**Comment by eea03** [comment]
I have already given it a little thought and I don't think there should be problems with using this data unit in module-test. We will discuss it.

**Comment by tomas-knap** [comment]
Note regarding module-test - support for testing modules should be in the future in plugins-devEnv, as this is the right place where it should be put (just to take that into account)

**Comment by tomas-knap** [comment]
Will review tomorrow.

**Comment by tomas-knap** [comment]
Regarding putting dataunits into separate modules, I think it is a good programming approach which also simplifies maintenance and is recommended way when new dataunits are created. Furthermore, relational data unit is optional data unit, which certain deployments do not need, or even do not want to support. So all the implementation logic should not be in commons-app just because it can be initialized by Spring.

**Comment by eea03** [comment]
Actually, the only relational data unit class in commons-app is RelationalRepositoryManager, which just configures the relational data unit, or to be more precise, it configures the underlying database.
It also holds already created databases for a pipeline as pipeline and all relational data units share the same database. 
This called from DataUnitFactory, which is also placed in commons-app so it looked a proper place to locate such configuration class.
Otherwise the relational data unit is independent and can also be created without this configuration class so it can be easily unit tested and module tested.

Also, I think @mkl-eea-sk spoke about two modules in UV Core for each data unit, even when dataunit-file is empty and dataunit-rdf seemed obsolete to me. So I implemented relational data unit only in one module - dataunit-relational-impl.

**Comment by eea03** [comment]
Relational data unit implementation will be extended by a new internal database type - embedded database in file mode. This will also be a default used internal database and it will prevent JVM memory problems with large data. However in memory database will still be available to use if needed. 

So the review of this feature can be posponed until this new database type is implemented

**Comment by tomas-knap** [comment]
Ok, I already reviewed. 
+1 for file mode, because we won't fit into memory always

Two comments: 
1) For interfaces, do not use ConnectionProviderIF pattern, use just ConnectionProvider and, for the implementation ConnectionProviderImpl. Such pattern is used in the rest of the code. 
2) Please add comments to interfaces and public classes, e.g., 
RelationalRepositoryManager, RelationalDataUnitIterationEager, and also at least to the methods in interfaces and methods of public classes not implementing any interface. 

Otherwise I liked the code, unit tests.

**Comment by eea03** [comment]
OK, I finished the implementation of the file mode of relational data unit.
It is user and unit tested (both modes).

I also incorporated both your comments. 
I tried to supplement comments for all public classes and interfaces and all public methods and constructors.

So please review these issues and hopefully we can merge this branch afterwards.

**Comment by skrchnavy** [comment]
@tomas-knap to review

**Comment by skrchnavy** [comment]
Depends on UnifiedViews/Plugin-DevEnv#13

**Comment by skrchnavy** [comment]
@tomas-knap please provide final review

**Pull request merged**
