### PR TITLE
Cryptography support in Core

### PR DESCRIPTION
**Pull request by skrchnavy**
Based on #320

### CODE REVIEW

**Comment by skodape** [comment]
+1 for: optional value in configuration (there is space for some best-practice place to put these binding to), although a comment that what this line does in config properties would be nice + all side effects (import/export).

I don't like the runtime exceptions - red message for user :( 

Just to made thinks clear: How does this work with export/import?

**Comment by skrchnavy** [comment]
@eea01  please answer @skodape question about import/export.
- If I remember, configuration is exported and imported cryptic
- when proper key is installed on new system, it is there decoded.

**Comment by eea01** [comment]
Cryptography does not intercept export nor import.

**Comment by skodape** [comment]
But I can export pipeline on one system, import to another and run the pipeline.  And if there is a DPU that utilize this feature then I get wrong password or exception or .. ? The question was on this behaviour.

**Comment by tomas-knap** [comment]
See https://team.eea.sk/wiki/display/OD/Cryptography+support+for+DPUs

This pull request should NOT be merged. To implement cryptography, please finalize the branch https://github.com/UnifiedViews/Plugin-DevEnv/commits/feature/cryptographyHelper, which I sketched for you. All is implemented in two classes.

**Pull request closed without merging**
