### PR TITLE
Internationalisation support in UV Frontend / Backend

### PR DESCRIPTION
**Pull request by skrchnavy**
this is related to issue #217 - Internationalisation of unified views core.

### CODE REVIEW

**Comment by tomas-knap** [comment]
One comment:

I did not like that every module contains practically the same Messages class. Isn't there a possibility to set it once (for everything) or twice (for Core and dataunit) so that it uses always proper path to bundles in every module? The problems are that developer has to think always to include such class to the module with i18n support, when the logging message for "no key" needs to be changed, it has to be changed in all modules. 

Agree we can add support for localization as a service later, so I would keep it as it is.

**Comment by eea02** [comment]
At first, I have used classical Spring aproach, which you have mentioned above, but then I quickly realized that in many occasions I needed static access to message source. Many classes have static methods, that I needed to localize, and there, spring context cannot be retrieved.

**Comment by tomas-knap** [comment]
@eea02, Miroslave, so you basically created two types of LocaleHolders, one for core, one for dataunits?

 Regarding 1) (Messages class in every module), did you find any nonSpring solution? It would be also possible to have abstract class AbstractMessages and override only the initializeResourceBundle() method in every module, but the value added is not that big.

**Comment by eea02** [comment]
@tomas-knap yes, now we will have 2 LocaleHolders. I agree with you, that static approach is least preferable, but for now, it is the only solution.

**Pull request closed without merging**
