### PR TITLE
Feature request: delete pipeline executions

### LINKED ISSUE #362: Feature request: delete pipeline executions
Currently (791cdce39008b4553e068ba1e2f42a90b7001164), there's no way how to delete individual pipeline executions other than directly removing files from `general.workingdir` and rows from database. Intermediate data produced by pipelines thus keeps on piling and takes up valuable disk space.

One possible solution would be to add a "delete" button to each row in the list of pipeline executions in the Execution monitor.

### PR DESCRIPTION
**Pull request by pgo-eea-sk**
Resolves #362

### CODE REVIEW

**Comment by tomas-knap** [comment]
There are issues reported at https://github.com/UnifiedViews/Core/issues/362

**Comment by mbl-eea-sk** [comment]
Done with exception of the bug with unexpected error when trying to re-click Execution monitor tab - resolving this might take a bit longer, test the other issues please.

**Comment by tomas-knap** [comment]
Summary of what is missing: 
1) bug reported under https://github.com/UnifiedViews/Core/issues/362 with NullPointerException (is it reproducible?)
2) Validator - so that I can insert only "0+" to the "number of days" field

**Comment by mbl-eea-sk** [comment]
1. Method pipelineFacade.delete(fpe) is undeclared - IDE shows error and application is not compiled
2. The bug is reproducable, I still have not found what exactly causes it, perhaps someone who participated at Core development from beginning could find this more easily
3. Validator - do we need it? When user inserts negative number it deletes all records older from that "future" day, which logically do not exist so the effect is the same as if "0" was inserted. If so we can do this as @mkl-eea-sk drafted in #362
4. Labels have been shortened

**Comment by tomas-knap** [comment]
Regarding 2. (Validator), yes, this could be solved as @mkl-eea-sk proposed in #362.

**Pull request merged**
