### PR TITLE
API: new function returning pipelines visible for organization

### PR DESCRIPTION
**Pull request by mvi-eea-sk**
resolves UV side of: OpenDataNode/open-data-node#196

new api function with path /pipelines/visible?userExternalId=ID, that returns all pipelines:
* user / organization owns
* or that aren't private

motivation: [sto_5v2: New associated pipeline as modified copy of an existing pipeline](https://utopia.sk/wiki/display/ODN/sto_5v2%3A+New+associated+pipeline+as+modified+copy+of+an+existing+pipeline)
* in current implementation user can only copy pipeline his organization owns

Note: I will update wiki page after merge

### CODE REVIEW

**Comment by tomas-knap** [comment]
@mvi-eea-sk  Is this ready for testing?

**Comment by mvi-eea-sk** [comment]
@tomas-knap yes, you can test it
but if you want to test integration with CKAN too, you need to use [feature/copy_pipe_of_another_org](https://github.com/OpenDataNode/ckanext-odn-pipeline/commit/b303967c77e7a944cf40b9b6ad6818f346644682)

**Comment by tomas-knap** [comment]
@skrchnavy Is this for 2.2.0?

**Comment by tomas-knap** [comment]
I tested just the master component - that the REST service is working

**Pull request merged**
