### PR TITLE
Repaired theme configuration bug

### PR DESCRIPTION
**Pull request by skrchnavy**
fix of  #302

### CODE REVIEW

**Comment by skrchnavy** [comment]
@tomas-knap @skodape : please check if the fix is OK

**Comment by skodape** [comment]
May I ask a question? If we have this solution we we need this:
https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/ODCSApplicationServlet.java#L103

?

**Comment by eea01** [comment]
[Pipeline canvas](https://github.com/UnifiedViews/Core/blob/develop/frontend/src/main/java/cz/cuni/mff/xrg/odcs/frontend/gui/components/pipelinecanvas/js_pipelinecanvas.js#L290) needs to know which theme to use.

**Comment by skodape** [comment]
ok, thanks

**Pull request merged**
