### PR TITLE
Add  LICENSE.md to modules, adjust README.md and add license headers to all sourcefiles

### LINKED ISSUE #441: improve licensing information in source code
UnifiedViews core is licensed using two set of licenses: GPLv3 and LGPLv3.

High level-overview of licensing, describing also what parts are actually LGPLv3 and what GPLv3 is mentioned in https://github.com/UnifiedViews/Core/blob/master/README.md#licenses .

But http://www.gnu.org/licenses/gpl-howto.html states that also *"The copying permission statement should come right after the copyright notices ... This statement should go near the beginning of every source file, close to the copyright notices."*

So, to improve licensing information as per FSF recommendations (to avoid potential legal difficulties, etc.) adding short copyright and licensing notices as comment at the beginning of all non-trivial source code files is needed.

### PR DESCRIPTION
**Pull request by mkl-eea-sk**
Resolves #441

### CODE REVIEW

**Comment by tomas-knap** [comment]
Ok, except for module-test, which should be licensed under LGPL, because:
* it was licensed under such license up to now
* it is directly used by the DPU, when testing the DPUs during development. So in order to avoid any potential issues when module-test dependency remains in commercial DPUs, lets leave it under LGPL. 

So please change module-test/LICENSE file, also please update headers of module-test source files to LGPL

The root LICENSE file can be removed (as the LICENSE is defined in each module)

**Comment by skrchnavy** [comment]
Is module test distributed with dpu? By my opinon it is used as application not as an library so gpl shall be enough.

**Comment by tomas-knap** [comment]
No, module-test is not bundled with the DPU, but it is used for testing the DPU. 

Lets leave it as LGPL, because 1) it was license under LGPL up to now, so in order to change the license, approval of the authors (or those holding the rights of the authors) would be needed. 2) LGPL for sure does not bring any issues when used by non-opensource DPUs and it does not bring any substantial disadvantage when compared with GPL other than the fact that in certain cases other subjects may prepare library extending module-test without providing the extension back as open source.

**Comment by skrchnavy** [comment]
Modele-test uses other UV modules so also those modeles shall be LGPL. Probably only frontend and backend are then GPL

**Comment by mkl-eea-sk** [comment]
What about extracting module-test to plugin-devenv ? with the dataunit 
implementations

**Comment by tomas-knap** [comment]
No, we will not put implementations of dataunits to Plugins-devEnv. 

We should decide among these two variants: module-test under LGPL or GPL

**Comment by tomas-knap** [comment]
As I was further checking it, we can leave it as LGPL, because module-test uses other libraries (dataunit-implementations, commons-app, dataunit), but such libraries are not included in the program (module-test.jar). If module-test would be licensed as GPL, that should be also safe, as module-test is not packed with the DPU bundles. 

So both options are possible. Since it was from the beginning licensed under LGPL, I would suggest to keep it as it is, as change of the license requires approval from the authors/institutions holding the rights. Getting any approval from Charles Uni is quite hard, so lets keep it as it is.

**Comment by tomas-knap** [comment]
So to solve the pull request: 

1) Please change module-test/LICENSE file, also please update headers of module-test source files to LGPL
2) The root LICENSE file can be removed (as the LICENSE is defined in each module)

**Comment by mkl-eea-sk** [comment]
module-test : LGPL, others: GPL.
pom.xml <license> tag added
plugin to check licenses in .java files added! build should fail if developer forgets to add license header.
licenses in .java not in .properties

**Pull request merged**
