### PR TITLE
Feature/dpu import api

### PR DESCRIPTION
**Pull request by eea02**
For deployment, and automated tests we need a way to import DPU templates without GUI. This feature adds possibility to upload DPU JAR file through existing REST API Master.

### CODE REVIEW

**Comment by skodape** [comment]
Is the purpose of this only to upload DPU for testing and deployment? As if so, is is necessary to use all checks use by frontend? Can't we simply  assume that user know what is doing if he is using this API?

**Comment by skodape** [comment]
Idea is, if it is inevitable to move dependencies from frontend to common-app. As by this we bring the necessity of Vaadin to backend. True, it's presented even now, but only because of OSGI and can be removed once Vaadin is made optional for DPUs or Vaadin OSGI libs are added to backend's module lib directory.

**Comment by eea02** [comment]
My intension was to reuse existing code in frontend also in the API. Therefore I moved it into commons module shared by all. As far as I know, I haven't introduced any dependency on vaadin libraries by this move.
Purpose is only for testing and deployment.

**Comment by skodape** [comment]
Not introduced but probably used, it's about class:
https://github.com/UnifiedViews/Core/blob/feature/dpu_import_api/commons-app/src/main/java/cz/cuni/mff/xrg/odcs/commons/app/dpu/validator/ConfigurationDialogValidator.java
as this utilized (intransitively) Vaadin to create a dialog.
This is useful if you want to make sure that DPU is working, but if master is used by trusted source, then this might not be necessary - question for architect, @tomas-knap .

Just one more question,note:
Have you tried to just add record to database and copy DPU to its directory - for purpose of deploy that may be enough?
If you want to replace DPU then commons-app (create file with the right prefix) should also be enough.

**Comment by eea02** [comment]
OK, now I understand which part you meant. Yes, I wanted to make sure that DPU is valid and working. Also I did not know what all kind of operations are done when importing a DPU and this was a safest way. 
   If you are sure that just adding entry to database and copying file to right folder is enough, maybe we can avoid moving these classes from frontend to commons-app.

**Comment by skrchnavy** [comment]
@skodape installing of DPU via SQL script would add maintenance complexity - dependency on changes of DB schema and also configuration changes. And when new DB is supported also to write specific installation script for it.
There shall be reduced number of entry points / services that supports same functionality, when we have import DPU service then this shall be used from all clients.

**Comment by tomas-knap** [comment]
Please adjust as state below, there is no need to move the classes from frontend to commons-app, it is even not desired (DPUTemplateWrap was meant to be helper for frontend for manipulation of DPUs in frontend).
  
Steps to be done: 
1) master/api/DPUResource.java, lines 79-85 should be removed, it is enough to call: 
dpuManipulator.create(jarFile, dpuName)
2) Rollback commits https://github.com/UnifiedViews/Core/commit/1ce8635e55e57072baadebf87a2f5c5e53d14532 and https://github.com/UnifiedViews/Core/commit/d7361aa7236b6d8de709dc34f1ce542957b23b07, classes like DPUTemplateWrap, DPURecordWrap etc. were designed as helpers for manipulation with DPUs in frontend. REST API must not use any frontend classes, because there is no reason for that. 

Note: Calling dpuManipulator.create(jarFile, dpuName) ensures that the DPU is stored to DB, copied to proper location. @skrchnavy's comment is also incorporated, as dpuManipulator is using DPUTemplate object being persisted to DB using ORM.

**Comment by eea02** [comment]
I have reverted the previous commits, and changed implemetation of API based on comments from @tomas-knap post.

**Comment by tomas-knap** [comment]
Thanks!

**Pull request merged**
