### PR TITLE
Escape button closes ConfirmDialog, pipeline view and dpu template view, confirm dialog with Save, Discard and Cancel buttons (cancel prevents out-navigation)

### LINKED ISSUE #240: Frontend: Copy & Close discards changes without warning
Frontend: Copy & Close in pipeline editor discards changes without warning

### LINKED ISSUE #370: Save or Discard changes popup window performs a default action instead of cancelling
Scenario:
1. I'm editing a pipeline.
2. I click somewhere else (let's say "DPU templates" in menu) which brings up a popup (Save pipeline or Discard changes). So far so good.
3. Now when I click the little cross of modal popup window (I want to close it), the application surprisingly doesn't stay on the current screen but **proceeds to next screen (in our case: DPU templates screen) and performs the default action** (save the pipeline if I remember correctly).

I find this counter-intuitive. This behavior might lead to users' pipelines being saved when not intended to (this was my case on several occasions). Standard behavior in all types of GUIs that I observed is that cancellation of this kind of popup window leaves the user on current screen and their work is untouched. User must make an explicit choice whether to save or discard the changes.
I suggest this be changed to function in a way users are accustomed to.
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

### PR DESCRIPTION
**Pull request by mkl-eea-sk**
Resolve #370
Resolve #240
upgrade of confirmdialog to 2.1.3 was needed to provide 3-way dialog
changed sk labels from "Ulozit"/"Zrusit zmeny" to 3-way: "Ulozit"/"Zahodit zmeny"/"Zrusit"
changed en labels from "Save"/"Discard" to 3-way: "Save"/"Discard"/"Cancel"

### CODE REVIEW

**Comment by tomas-knap** [comment]
If I create new pipeline, add DPU, do not save it, click on a different menu item (e.g. DPU templates), then click "Cancel" in the confirm dialog:
1) I am  left on the pipeline edit screen (which is correct)
2) Menu item is pressed, although I am still on the pipeline edit screen

Solution: If I click on menu item, but transition to a different screen is cancelled, menu item must not be pressed/selected (see below - DPU templates, Execution Monitor, Scheduler is selected): 

screen shot 2015-07-19 at 23 45 17

**Comment by tomas-knap** [comment]
Summary regarding copy and copyAndClose: 

For each case (copy and copyAndClose), there should be two possible confirm dialogs - one appears if unsaved pipeline is trying to be copied, the second appear when someone adjusted the pipeline after I open the pipeline, but before I tried to copy it. So there are 2 types of confirm dialogs for each case. Currently, in the localization, there is only one type for each case.

**Comment by tomas-knap** [comment]
Related: https://github.com/UnifiedViews/Core/issues/468

**Comment by mkl-eea-sk** [comment]
Thank you for providing requirements for issue #240 which were missing until now.

**Comment by mkl-eea-sk** [comment]
Resolved all comments

**Comment by skrchnavy** [comment]
@mkl-eea-sk please merge develop branch to resolve conficts

**Comment by tomas-knap** [comment]
One problem (see above), than it can be merged

**Pull request merged**
